extends:
  - mealsup
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript

plugins:
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

settings:
  react:
    version: detect

env:
  browser: true

rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/member-delimiter-style': off
